trigger: none

pr:
  branches:
    include:
    - master
  paths:
    include:
    - terraform/*
    - pipelines/ansible-pr.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: ansible

steps:

- script: |
    az login --service-principal --username $(SP_CLIENT_ID) --password $(SP_CLIENT_SECRET) --tenant $(SP_TENANT_ID)
    az account set --subscription $(AZURE_SUBSCRIPTION_ID)
    az aks get-credentials --name $(AZURE_AKS_NAME) --resource-group $(AZURE_RG_NAME)
    cd ansible
    export AZURE_AKS_NAME=$(AZURE_AKS_NAME)
    ansible-playbook -i hosts site.yml --syntax-check
    ansible-playbook -i hosts site.yml
  displayName: 'ansible '
