trigger: none

pr:
  branches:
    include:
    - master
  paths:
    include:
    - terraform/*
    - pipelines/terraform-pr.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: terraform

steps:
- script: |
    terraform --version
  displayName: 'Check Terraform Version'

- script: |
    # export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)
    # export ARM_CLIENT_ID=$(SP_CLIENT_ID)
    # export ARM_CLIENT_SECRET=$(SP_CLIENT_SECRET)
    # export ARM_TENANT_ID=$(SP_TENANT_ID)
    cd terraform/environments
    terraform init -backend-config "storage_account_name=$(TF_STORAGE_ACCOUNT_NAME)" -backend-config "container_name=$(TF_CONTAINER_NAME)" -backend-config "key=$(TF_KEY)" -backend-config "access_key=$(TF_ACCESS_KEY)"
    terraform plan
  env:
    ARM_SUBSCRIPTION_ID:     $(AZURE_SUBSCRIPTION_ID)
    ARM_CLIENT_ID:           $(SP_CLIENT_ID)
    ARM_CLIENT_SECRET:       $(SP_CLIENT_SECRET)
    ARM_TENANT_ID:           $(SP_TENANT_ID)
    TF_VAR_prefix:           $(PREFIX)
    TF_VAR_sp_client_id:     $(AKS_CLIENT_ID)
    TF_VAR_sp_client_secret: $(AKS_CLIENT_SECRET)
  displayName: 'Terraform Plan'
